name: Content Change Notification

on:
  push:
    paths:
      - 'content/posts/**'
      - 'content/data/**'
      - 'content/images/**'
      - 'content/_incoming/**'
    branches:
      - 'main'

jobs:
  notify:
    runs-on: ubuntu-latest
    # Don't run this workflow if the commit message contains [skip ci], [deploy], or [workflow]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[deploy]') && !contains(github.event.head_commit.message, '[workflow]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            content/posts/**
            content/data/**
            content/images/**
            content/_incoming/**
            
      - name: List all changed files
        run: |
          echo "Changed files:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done
          echo "Added files:"
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file"
          done
          
      - name: Send Slack deployment approval request
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 Content changes detected!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repo:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* <${{ github.event.head_commit.url }}|${{ github.event.head_commit.id }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Changed files:*\n```${{ steps.changed-files.outputs.all_changed_files }}```"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Would you like to process and deploy these changes?"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Process Content"
                      },
                      "style": "primary",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/workflows/blog-content-pipeline.yml/dispatch?inputs[source_commit]=${{ github.sha }}&inputs[source_branch]=${{ github.ref_name }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Changes"
                      },
                      "url": "${{ github.event.head_commit.url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 